CREATE schema IF NOT EXISTS `HEALTH_SYSTEM` default char set utf8;
USE `HEALTH_SYSTEM`;

DROP TABLE IF EXISTS `FILES`;
DROP TABLE IF EXISTS `CLIENT`;

CREATE TABLE `CLIENT` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `NAME` VARCHAR(20) DEFAULT NULL,
  `SURNAME` VARCHAR(30) DEFAULT NULL,
  `EMAIL` VARCHAR(50) NOT NULL,
  `PASSWORD` CHAR(40) NOT NULL,
  `DATE_OF_BIRTH` DATETIME NOT NULL,
  `PHONE` VARCHAR(11) DEFAULT NULL,
  `HEIGHT` DOUBLE NOT NULL,
  `WEIGHT` DOUBLE NOT NULL,
  `GENDER` ENUM('MALE','FEMALE') NOT NULL,
  PRIMARY KEY (`ID`)
);

CREATE TABLE `FILES` (
  `FILE_ID` INT NOT NULL AUTO_INCREMENT,
  `FILE_NAME` VARCHAR(128) DEFAULT NULL,
  `FILE_DATA` LONGBLOB,
  `CLIENT_ID` INT NOT NULL,
  PRIMARY KEY (`FILE_ID`),
  FOREIGN KEY (`CLIENT_ID`) REFERENCES `CLIENT`(`ID`)
)
